### ISSUE TITLE
Using Google Fonts breaks use w/o Library

### ISSUE THREAD

**Issue by devallibus** [mudgen/runcss#2]
Adding a stylesheet link like Google Fonts breaks it, displaying nothing.

I am using the script method without any library.

It is necessary to use the import method for it to work.

**Comment by dragonwocky** [comment]
It looks like if the first stylesheet on a page is a `<link>` and not a `<style>` then RunCSS is trying to access/modify a stylesheet that it doesn't have permission for? I bypassed it by adding an empty style tag to my `<head>` but still odd.
![image](https://user-images.githubusercontent.com/16874139/97577759-f033f500-1a43-11eb-9c29-787ab020dec3.png)

**Comment by dragonwocky** [comment]
Hi, this is fixed but not yet pushed to unpkg. Until then, you can use this URL for the latest version: https://cdn.statically.io/gh/mudgen/runcss/master/src/runcss.min.js
