### ISSUE TITLE
Is this up to date with Tailwind 3.3.3?

### ISSUE THREAD

**Issue by sebastianwebb** [mudgen/runcss#23]
Love the idea behind this Nick. I see that hasn't been an update in 3 years. I was just wondering if it supports all of the latest Tailwind classes at the time of writing (Sept 19, 2023). Or if this project is no longer active...

Thanks!
Sebastian

**Comment by lucafabbian** [comment]
Hi, I'm Luca, the new project mantainer. Look at the latest rewrite - it should be on pair with Tailwind 3.3 !  :wink:
