### ISSUE TITLE
Probleme with .z-20

### ISSUE THREAD

**Issue by Tindome** [mudgen/runcss#4]
Hello,

Just tryout the script, (from source) and i have a little problem with property .z-20, it don't produce  z-index: 20; it produce nothing
Did i miss something ?

By the Way in documentation : https://github.com/mudgen/runcss#pseudo-class-variants you sometimes invert letters in the word "pseudo"

Thanks for your work

**Comment by dragonwocky** [comment]
Hi, this is fixed but not yet released. Until then, you can use this URL for the latest version: `https://cdn.statically.io/gh/mudgen/runcss/master/src/runcss.min.js`
