### ISSUE TITLE
configure not changing colors

### ISSUE THREAD

**Issue by mynameisvasco** [mudgen/runcss#5]
Hello, I am using this library and I faced this issue.
I am running the code bellow before processClasses and elements colors doesn't change. 

`configure({
    colors: {
      gray: {
        50: "#F7FAFC",
        100: "#EDF2F7",
        200: "#E2E8F0",
        300: "#CBD5E0",
        400: "#A0AEC0",
        500: "#718096",
        600: "#4A5568",
        700: "#2D3748",
        800: "#1A202C",
        900: "#171923",
      },
    },
  });`

**Comment by mudgen** [comment]
Thanks for reporting this. I need to look into this.

**Comment by dragonwocky** [comment]
I've found the same problem: it only changes colours at root level, not sub-colours.
Semi-related question (let me know if this should be moved to a different issue), is there a way to force re-processing of classes/colours? E.g. if I wanted to change colours based on light mode/dark mode.

**Comment by dragonwocky** [comment]
This is now fixed but not yet released. Until then, you can use this URL for the latest version: `https://cdn.statically.io/gh/mudgen/runcss/master/src/runcss.min.js`
