### ISSUE TITLE
Colors (rgba)

### ISSUE THREAD

**Issue by Tindome** [mudgen/runcss#7]
I wanna create a div with a custom background rgba color how could i ?
first i try this way

```js
RunCSS.configure({
	  colors: {
		smoke: {
			lightest: 	rgba2hexP('rgba(0, 0, 0, 0.1)'),
			lighter: 	rgba2hexP('rgba(0, 0, 0, 0.25)'),
			light: 		rgba2hexP('rgba(0, 0, 0, 0.4)'),
			dark: 		rgba2hexP('rgba(0, 0, 0, 0.6)'),
			darker:		rgba2hexP('rgba(0, 0, 0, 0.75)'),
			darkest: 	rgba2hexP('rgba(0, 0, 0, 0.9)')
		}
	  }
	})
```

rgba2hexP is a custom function for conversion of string rgba to hex, but fail (8digit hex instead of 6)

so i do it this way

```
RunCSS.configure({
	  colors: {
		smoke: rgbToHex(0,0,0)
	   }
	})
```

```html
	<div class="fixed pin z-50 overflow-auto bg-smoke flex " style="--background-color-opacity:0.4;">
		test of content
	</div>
```

is this the correct way or did i miss something

**Comment by dragonwocky** [comment]
you can style the background opacity via https://tailwindcss.com/docs/background-opacity

if I have some time I might be able to update runcss to support 8 char hexes

**Comment by Tindome** [comment]
houps my bad i just use and old tailwind tuto as a template and obviously it seems to be deprecated
