### ISSUE TITLE
tailwind height problem

### ISSUE THREAD

**Issue by Tindome** [mudgen/runcss#8]
property : https://tailwindcss.com/docs/height
seem not to be functionnal 

```html
<svg class="h-12 w-12 fill-current text-gray-500 hover:text-gray-900 bg-opacity-100" 
...
```

h-12 and w-12 are not exported to generated css

**Comment by ramezrafla** [comment]
There is a bug in runCSS for SVG
In `processClasses`, right above `if (typeof classes == 'string')` add this:
```
if (typeof classes === 'object') classes = classes.baseVal
```

**Comment by lucafabbian** [comment]
Fixed in new docs :)
